import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import ClerkProvier from "@/providers/clerk-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvier>
        <body className={`${inter.className} dark bg-dark-2 antialiased`}>
          {children}
          <Toaster
            toastOptions={{
              className: "",
              style: {
                background: "#1C1F2E",
                color: "white",
              },
            }}
          />
        </body>
      </ClerkProvier>
    </html>
  );
}
